### ISSUE TITLE
issue where text is not displayed

### ISSUE THREAD

**Issue by dsyme** [TimLariviere/ElmishPlanets#1]
When I start _without_ debugging on Android I get this:

![image](https://user-images.githubusercontent.com/7204669/44999834-11117480-afb8-11e8-8032-6b7cabc83651.png)

and this:

![image](https://user-images.githubusercontent.com/7204669/44999840-1cfd3680-afb8-11e8-83f9-baa80dbe3d57.png)

I'm not sure what's going on, it might just be my machine. The same thing happens even if I use explicit `textColor` though for the labels.

**Comment by TimLariviere** [comment]
Strange, I don't reproduce it...
Are you using VS 4 Mac or Visual Studio ?

I force all labels to `textColor=Color.White` anyway. (`View.Label(...).WhiteText()`)

**Comment by dsyme** [comment]
Yes very odd. Using vs15.7

**Comment by TimLariviere** [comment]
@dsyme Do you still have the issue with the latest version?
Recently used Paket, so you might need to do a `paket restore`

**Comment by dsyme** [comment]
closing out, I haven't seen this
